### ISSUE TITLE
How can I get more data like this ?

### ISSUE THREAD

**Issue by PhilWallace** [airbus-seclab/cpu_rec#8]
I would like to know how the corpus data were generated. For one kind of CPU architecture, are the data from one single binary? Were they compiled by the same compiler? 

Thanks very much.

**Comment by LRGH** [comment]
This is described in the second appendix in https://github.com/airbus-seclab/cpu_rec/blob/master/doc/cpu_rec_sstic_english.md, which I did not translate (yet).
Very often, a single binary was used.
Usually, the compiler does not matter. The exception is for 6502.

**Comment by LRGH** [comment]
Now the second appendix is translated :-)
